import type { Metadata } from "next";
import {  Karla,  Liu_Jian_Mao_Cao } from "next/font/google";
import "./globals.css";


const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

const logo = Liu_Jian_Mao_Cao({
  weight: "400",
  variable: "--font-logo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Escapate a San Carlos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable}  ${logo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
